INSERT INTO customers (customer_id, name, email, gender, age, city, country) VALUES
(1, 'Elijah Brown', 'elijah.brown1@example.com', 'M', 65, 'Berlin', 'Germany'),
(2, 'Abigail Wilson', 'abigail.wilson1@example.com', 'F', 61, 'Vancouver', 'Canada'),
(3, 'Amelia Gupta', 'amelia.gupta1@example.com', 'M', 20, 'New York', 'USA'),
(4, 'Avery Dubois', 'avery.dubois1@example.com', 'F', 56, 'New York', 'USA'),
(5, 'Priya Verma', 'priya.verma1@example.com', 'F', 32, 'Tokyo', 'Japan'),
(6, 'Emily Lee', 'emily.lee1@example.com', 'M', 62, 'Sydney', 'Australia'),
(7, 'Evelyn Ramirez', 'evelyn.ramirez1@example.com', 'M', 66, 'Paris', 'France'),
(8, 'John Gonzalez', 'john.gonzalez1@example.com', 'M', 40, 'Boston', 'USA'),
(9, 'Zoey Garcia', 'zoey.garcia1@example.com', 'F', 64, 'Tokyo', 'Japan'),
(10, 'John Hernandez', 'john.hernandez1@example.com', 'F', 53, 'Berlin', 'Germany'),
(11, 'Alice Campbell', 'alice.campbell1@example.com', 'F', 54, 'London', 'UK'),
(12, 'Noah Robinson', 'noah.robinson1@example.com', 'Other', 67, 'Berlin', 'Germany'),
(13, 'Avery Gonzalez', 'avery.gonzalez1@example.com', 'M', 42, 'Berlin', 'Germany'),
(14, 'Wyatt Lee', 'wyatt.lee1@example.com', 'M', 41, 'Paris', 'France'),
(15, 'Henry Martinez', 'henry.martinez1@example.com', 'M', 56, 'Shanghai', 'China'),
(16, 'Sofia Lee', 'sofia.lee1@example.com', 'M', 47, 'Sydney', 'Australia'),
(17, 'Valentina Lewis', 'valentina.lewis1@example.com', 'F', 61, 'Paris', 'France'),
(18, 'Mason Robinson', 'mason.robinson1@example.com', 'F', 70, 'New York', 'USA'),
(19, 'Camila Wright', 'camila.wright1@example.com', 'F', 22, 'London', 'UK'),
(20, 'Luca Green', 'luca.green1@example.com', 'F', 31, 'Shanghai', 'China'),
(21, 'Charles Jackson', 'charles.jackson1@example.com', 'M', 34, 'Toronto', 'Canada'),
(22, 'Valentina King', 'valentina.king1@example.com', 'M', 65, 'Mumbai', 'India'),
(23, 'Hans Khan', 'hans.khan1@example.com', 'Other', 41, 'London', 'UK'),
(24, 'Abigail Lefevre', 'abigail.lefevre1@example.com', 'F', 49, 'San Francisco', 'USA'),
(25, 'Elijah Martin', 'elijah.martin1@example.com', 'F', 58, 'Toronto', 'Canada'),
(26, 'Dylan Rodriguez', 'dylan.rodriguez1@example.com', 'F', 42, 'Sydney', 'Australia'),
(27, 'Brooklyn Allen', 'brooklyn.allen1@example.com', 'F', 53, 'Boston', 'USA'),
(28, 'Elijah Wright', 'elijah.wright1@example.com', 'M', 67, 'Shanghai', 'China'),
(29, 'Hannah Zhang', 'hannah.zhang1@example.com', 'M', 28, 'Tokyo', 'Japan'),
(30, 'Zoey Dubois', 'zoey.dubois1@example.com', 'F', 66, 'Toronto', 'Canada'),
(31, 'Charlotte Hill', 'charlotte.hill1@example.com', 'F', 71, 'Shanghai', 'China'),
(32, 'Scarlett Martin', 'scarlett.martin1@example.com', 'M', 41, 'Chicago', 'USA'),
(33, 'Mei Carter', 'mei.carter1@example.com', 'F', 56, 'Paris', 'France'),
(34, 'Elijah Campbell', 'elijah.campbell1@example.com', 'F', 74, 'Boston', 'USA'),
(35, 'Daniel Davis', 'daniel.davis1@example.com', 'F', 33, 'Los Angeles', 'USA'),
(36, 'Lucas Hernandez', 'lucas.hernandez1@example.com', 'F', 64, 'Tokyo', 'Japan'),
(37, 'Arjun Taylor', 'arjun.taylor1@example.com', 'M', 26, 'Shanghai', 'China'),
(38, 'Diego Perez', 'diego.perez1@example.com', 'F', 34, 'Mexico City', 'Mexico'),
(39, 'Dylan Ramirez', 'dylan.ramirez1@example.com', 'F', 52, 'Chicago', 'USA'),
(40, 'Scarlett Flores', 'scarlett.flores1@example.com', 'F', 43, 'Shanghai', 'China'),
(41, 'Ezra Kim', 'ezra.kim1@example.com', 'M', 25, 'London', 'UK'),
(42, 'Penelope Williams', 'penelope.williams1@example.com', 'M', 55, 'Mexico City', 'Mexico'),
(43, 'Alexander Carter', 'alexander.carter1@example.com', 'F', 22, 'Vancouver', 'Canada'),
(44, 'Avery Rodriguez', 'avery.rodriguez1@example.com', 'F', 75, 'New York', 'USA'),
(45, 'Ethan Lefevre', 'ethan.lefevre1@example.com', 'F', 33, 'Berlin', 'Germany'),
(46, 'Victoria Taylor', 'victoria.taylor1@example.com', 'F', 64, 'Los Angeles', 'USA'),
(47, 'Giulia Rossi', 'giulia.rossi1@example.com', 'M', 33, 'Chicago', 'USA'),
(48, 'Mateo Harris', 'mateo.harris1@example.com', 'F', 24, 'San Francisco', 'USA'),
(49, 'Riley Gupta', 'riley.gupta1@example.com', 'F', 44, 'Tokyo', 'Japan'),
(50, 'Isabella Gonzalez', 'isabella.gonzalez1@example.com', 'F', 21, 'Sydney', 'Australia'),
(51, 'Charlotte Young', 'charlotte.young1@example.com', 'F', 30, 'London', 'UK'),
(52, 'Abigail Gupta', 'abigail.gupta1@example.com', 'M', 29, 'Berlin', 'Germany'),
(53, 'Ethan Chen', 'ethan.chen1@example.com', 'F', 69, 'Boston', 'USA'),
(54, 'Benjamin Miller', 'benjamin.miller1@example.com', 'F', 59, 'Mexico City', 'Mexico'),
(55, 'Amelia Walker', 'amelia.walker1@example.com', 'F', 28, 'Sydney', 'Australia'),
(56, 'Victoria Khan', 'victoria.khan1@example.com', 'M', 75, 'New York', 'USA'),
(57, 'Emily Roberts', 'emily.roberts1@example.com', 'F', 34, 'Los Angeles', 'USA'),
(58, 'Charles Torres', 'charles.torres1@example.com', 'F', 45, 'Vancouver', 'Canada'),
(59, 'Valentina Schmidt', 'valentina.schmidt1@example.com', 'M', 27, 'London', 'UK'),
(60, 'Mason Davis', 'mason.davis1@example.com', 'M', 65, 'Paris', 'France'),
(61, 'Hans Ricci', 'hans.ricci1@example.com', 'F', 50, 'Los Angeles', 'USA'),
(62, 'Jacob Davis', 'jacob.davis1@example.com', 'F', 50, 'San Francisco', 'USA'),
(63, 'Mia Rodriguez', 'mia.rodriguez1@example.com', 'M', 61, 'Boston', 'USA'),
(64, 'Harper Young', 'harper.young1@example.com', 'M', 55, 'Mumbai', 'India'),
(65, 'Lucas Verma', 'lucas.verma1@example.com', 'F', 60, 'Mumbai', 'India'),
(66, 'Joseph King', 'joseph.king1@example.com', 'F', 31, 'Shanghai', 'China'),
(67, 'Daniel King', 'daniel.king1@example.com', 'F', 43, 'Toronto', 'Canada'),
(68, 'David Kobayashi', 'david.kobayashi1@example.com', 'F', 38, 'Los Angeles', 'USA'),
(69, 'Ethan Johnson', 'ethan.johnson1@example.com', 'Other', 47, 'Mumbai', 'India'),
(70, 'Benjamin Martinez', 'benjamin.martinez1@example.com', 'F', 52, 'London', 'UK'),
(71, 'Logan Hall', 'logan.hall1@example.com', 'F', 74, 'San Francisco', 'USA'),
(72, 'Layla Torres', 'layla.torres1@example.com', 'F', 28, 'Tokyo', 'Japan'),
(73, 'David Johnson', 'david.johnson1@example.com', 'F', 60, 'Boston', 'USA'),
(74, 'Charlotte Moore', 'charlotte.moore1@example.com', 'F', 34, 'San Francisco', 'USA'),
(75, 'Diego Martin', 'diego.martin1@example.com', 'F', 35, 'Berlin', 'Germany'),
(76, 'Penelope Clark', 'penelope.clark1@example.com', 'F', 61, 'Shanghai', 'China'),
(77, 'Hiroshi Schmidt', 'hiroshi.schmidt1@example.com', 'F', 34, 'Los Angeles', 'USA'),
(78, 'Isabella Lopez', 'isabella.lopez1@example.com', 'F', 58, 'Sydney', 'Australia'),
(79, 'Noah Carter', 'noah.carter1@example.com', 'M', 39, 'Chicago', 'USA'),
(80, 'Zoey Lee', 'zoey.lee1@example.com', 'F', 65, 'Tokyo', 'Japan'),
(81, 'Dylan Johnson', 'dylan.johnson1@example.com', 'F', 25, 'San Francisco', 'USA'),
(82, 'Evelyn Jones', 'evelyn.jones1@example.com', 'F', 71, 'Paris', 'France'),
(83, 'James Zhang', 'james.zhang1@example.com', 'M', 26, 'New York', 'USA'),
(84, 'Noah Rivera', 'noah.rivera1@example.com', 'M', 31, 'Shanghai', 'China'),
(85, 'Charlotte Rivera', 'charlotte.rivera1@example.com', 'F', 67, 'Mexico City', 'Mexico'),
(86, 'Mateo Martin', 'mateo.martin1@example.com', 'M', 33, 'Boston', 'USA'),
(87, 'Aiden Singh', 'aiden.singh1@example.com', 'F', 19, 'Toronto', 'Canada'),
(88, 'Carter Singh', 'carter.singh1@example.com', 'F', 69, 'Shanghai', 'China'),
(89, 'Sofia Wright', 'sofia.wright1@example.com', 'F', 28, 'Chicago', 'USA'),
(90, 'John Jones', 'john.jones1@example.com', 'M', 72, 'Tokyo', 'Japan'),
(91, 'Charles Hall', 'charles.hall1@example.com', 'F', 37, 'Boston', 'USA'),
(92, 'Avery Lewis', 'avery.lewis1@example.com', 'M', 19, 'Shanghai', 'China'),
(93, 'Carter Scott', 'carter.scott1@example.com', 'Other', 73, 'San Francisco', 'USA'),
(94, 'Lily Hall', 'lily.hall1@example.com', 'M', 59, 'Mexico City', 'Mexico'),
(95, 'Arjun Nelson', 'arjun.nelson1@example.com', 'F', 19, 'San Francisco', 'USA'),
(96, 'Zoey Thompson', 'zoey.thompson1@example.com', 'M', 55, 'Berlin', 'Germany'),
(97, 'Pierre Zhang', 'pierre.zhang1@example.com', 'F', 40, 'Vancouver', 'Canada'),
(98, 'Luna Lefevre', 'luna.lefevre1@example.com', 'F', 25, 'Sydney', 'Australia'),
(99, 'Jackson Allen', 'jackson.allen1@example.com', 'M', 20, 'Vancouver', 'Canada'),
(100, 'Wei Sanchez', 'wei.sanchez1@example.com', 'M', 41, 'Sydney', 'Australia'),
(101, 'Carter Green', 'carter.green1@example.com', 'M', 60, 'Boston', 'USA'),
(102, 'David Dubois', 'david.dubois1@example.com', 'M', 37, 'Shanghai', 'China'),
(103, 'Camila Nguyen', 'camila.nguyen1@example.com', 'M', 53, 'Toronto', 'Canada'),
(104, 'John Thompson', 'john.thompson1@example.com', 'M', 57, 'Mumbai', 'India'),
(105, 'Diego Carter', 'diego.carter1@example.com', 'M', 37, 'Berlin', 'Germany'),
(106, 'Hans Adams', 'hans.adams1@example.com', 'M', 47, 'Tokyo', 'Japan'),
(107, 'Victoria Lefevre', 'victoria.lefevre1@example.com', 'F', 48, 'Chicago', 'USA'),
(108, 'Ella Hernandez', 'ella.hernandez1@example.com', 'F', 36, 'Mexico City', 'Mexico'),
(109, 'Alice Nelson', 'alice.nelson1@example.com', 'F', 23, 'Boston', 'USA'),
(110, 'Daniel Flores', 'daniel.flores1@example.com', 'M', 32, 'Chicago', 'USA'),
(111, 'Liam Garcia', 'liam.garcia1@example.com', 'F', 33, 'Tokyo', 'Japan'),
(112, 'Ethan Kobayashi', 'ethan.kobayashi1@example.com', 'F', 44, 'Los Angeles', 'USA'),
(113, 'Jackson Roberts', 'jackson.roberts1@example.com', 'M', 49, 'Sydney', 'Australia'),
(114, 'Emily Wilson', 'emily.wilson1@example.com', 'M', 67, 'Sydney', 'Australia'),
(115, 'Wei Tanaka', 'wei.tanaka1@example.com', 'M', 21, 'Mexico City', 'Mexico'),
(116, 'Harper Kobayashi', 'harper.kobayashi1@example.com', 'M', 26, 'Chicago', 'USA'),
(117, 'Mei Green', 'mei.green1@example.com', 'M', 66, 'Los Angeles', 'USA'),
(118, 'Hiroshi Gupta', 'hiroshi.gupta1@example.com', 'F', 71, 'Los Angeles', 'USA'),
(119, 'Jacob Rossi', 'jacob.rossi1@example.com', 'F', 46, 'Berlin', 'Germany'),
(120, 'Lily Schmidt', 'lily.schmidt1@example.com', 'M', 58, 'London', 'UK'),
(121, 'Ethan Torres', 'ethan.torres1@example.com', 'M', 33, 'Berlin', 'Germany');
