INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (1, 'Inception', 'Drama', 1971, 'Alfonso Cuaron', 7.3, 118, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (2, 'The Dark Knight', 'Drama', 2013, 'Alfonso Cuaron', 9.2, 101, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (3, 'Interstellar', 'Action', 1971, 'Quentin Tarantino', 7.2, 154, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (4, 'Pulp Fiction', 'Thriller', 2015, 'David Fincher', 8.6, 143, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (5, 'Kill Bill: Vol. 1', 'Fantasy', 2007, 'Makoto Shinkai', 8.9, 90, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (6, 'Parasite', 'Crime', 1991, 'Makoto Shinkai', 7.0, 187, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (7, 'Oldboy', 'Drama', 1975, 'Steven Spielberg', 6.8, 198, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (8, 'Spirited Away', 'Romance', 2021, 'Christopher Nolan', 8.7, 158, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (9, 'Your Name', 'Crime', 1975, 'Ridley Scott', 7.4, 170, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (10, 'Avengers: Endgame', 'Thriller', 2015, 'Quentin Tarantino', 6.6, 119, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (11, 'The Matrix', 'Drama', 1984, 'Pixar Team', 6.8, 125, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (12, 'Gladiator', 'Animation', 1980, 'Martin Scorsese', 7.6, 175, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (13, 'The Godfather', 'Drama', 2008, 'David Fincher', 7.0, 183, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (14, 'The Godfather Part II', 'Sci-Fi', 1999, 'Steven Spielberg', 7.3, 171, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (15, 'The Shawshank Redemption', 'Animation', 2023, 'Guillermo del Toro', 8.8, 119, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (16, 'The Departed', 'Animation', 1995, 'Makoto Shinkai', 6.7, 162, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (17, 'Django Unchained', 'Thriller', 2011, 'Francis Ford Coppola', 7.7, 172, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (18, 'The Hateful Eight', 'Sci-Fi', 1986, 'Bong Joon-ho', 7.2, 161, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (19, 'Titanic', 'Crime', 2007, 'Steven Spielberg', 7.6, 107, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (20, 'Avatar', 'Drama', 2018, 'Christopher Nolan', 9.1, 109, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (21, 'The Lion King', 'Crime', 2008, 'Quentin Tarantino', 7.7, 166, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (22, 'Frozen', 'Romance', 2005, 'Pixar Team', 9.3, 177, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (23, 'Inside Out', 'Romance', 2019, 'David Fincher', 7.5, 127, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (24, 'Toy Story', 'Sci-Fi', 1999, 'Christopher Nolan', 9.4, 182, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (25, 'Coco', 'Sci-Fi', 2002, 'Anthony Russo', 6.8, 170, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (26, 'Up', 'Thriller', 1979, 'Martin Scorsese', 8.8, 159, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (27, 'Finding Nemo', 'Animation', 2001, 'Christopher Nolan', 6.8, 136, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (28, 'Monsters, Inc.', 'Thriller', 1973, 'Hayao Miyazaki', 9.1, 100, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (29, 'WALL-E', 'Fantasy', 2022, 'Quentin Tarantino', 9.4, 158, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (30, 'Ratatouille', 'Sci-Fi', 2012, 'Francis Ford Coppola', 9.3, 111, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (31, 'The Silence of the Lambs', 'Crime', 1983, 'Anthony Russo', 8.1, 183, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (32, 'Se7en', 'Romance', 1995, 'David Fincher', 8.4, 146, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (33, 'Fight Club', 'Drama', 1985, 'Hayao Miyazaki', 6.7, 92, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (34, 'The Social Network', 'Thriller', 1970, 'Quentin Tarantino', 8.6, 97, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (35, 'The Irishman', 'Drama', 1972, 'Pixar Team', 7.5, 155, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (36, 'Goodfellas', 'Romance', 2012, 'Francis Ford Coppola', 7.1, 106, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (37, 'Casino', 'Thriller', 2020, 'Francis Ford Coppola', 8.9, 114, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (38, 'Heat', 'Drama', 2012, 'Steven Spielberg', 7.6, 142, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (39, 'The Prestige', 'Action', 2013, 'David Fincher', 9.5, 102, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (40, 'Memento', 'Crime', 2016, 'Martin Scorsese', 8.9, 103, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (41, 'Tenet', 'Thriller', 1982, 'Ridley Scott', 7.8, 144, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (42, 'Oppenheimer', 'Romance', 1999, 'Hayao Miyazaki', 9.1, 99, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (43, 'Amelie', 'Drama', 1973, 'David Fincher', 9.5, 197, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (44, 'Life Is Beautiful', 'Drama', 2018, 'Pixar Team', 7.2, 142, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (45, 'Cinema Paradiso', 'Fantasy', 1983, 'Pixar Team', 7.7, 97, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (46, 'Pan''s Labyrinth', 'Crime', 1970, 'Steven Spielberg', 7.3, 190, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (47, 'Roma', 'Romance', 1997, 'Alfonso Cuaron', 9.4, 190, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (48, 'Gravity', 'Sci-Fi', 1982, 'Makoto Shinkai', 7.2, 97, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (49, 'Children of Men', 'Animation', 1973, 'Christopher Nolan', 8.3, 154, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (50, 'Movie 50', 'Action', 2002, 'Quentin Tarantino', 9.1, 98, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (51, 'Movie 51', 'Thriller', 1995, 'Quentin Tarantino', 9.3, 162, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (52, 'Movie 52', 'Action', 2009, 'Quentin Tarantino', 7.8, 164, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (53, 'Movie 53', 'Romance', 1983, 'David Fincher', 8.6, 120, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (54, 'Movie 54', 'Crime', 1978, 'David Fincher', 8.4, 148, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (55, 'Movie 55', 'Drama', 1970, 'Francis Ford Coppola', 8.4, 162, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (56, 'Movie 56', 'Drama', 2004, 'Hayao Miyazaki', 8.0, 106, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (57, 'Movie 57', 'Drama', 1985, 'Martin Scorsese', 7.4, 146, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (58, 'Movie 58', 'Action', 2012, 'Pixar Team', 8.2, 174, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (59, 'Movie 59', 'Sci-Fi', 1986, 'Quentin Tarantino', 9.2, 185, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (60, 'Movie 60', 'Romance', 1988, 'James Cameron', 7.1, 133, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (61, 'Movie 61', 'Romance', 2002, 'Francis Ford Coppola', 7.3, 198, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (62, 'Movie 62', 'Drama', 2010, 'Steven Spielberg', 9.0, 95, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (63, 'Movie 63', 'Animation', 2019, 'Bong Joon-ho', 8.4, 123, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (64, 'Movie 64', 'Fantasy', 2005, 'Alfonso Cuaron', 7.8, 91, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (65, 'Movie 65', 'Drama', 2014, 'Anthony Russo', 6.9, 94, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (66, 'Movie 66', 'Sci-Fi', 1997, 'Bong Joon-ho', 6.6, 136, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (67, 'Movie 67', 'Animation', 1983, 'David Fincher', 7.2, 103, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (68, 'Movie 68', 'Crime', 2009, 'Alfonso Cuaron', 7.0, 120, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (69, 'Movie 69', 'Sci-Fi', 1996, 'Christopher Nolan', 7.0, 132, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (70, 'Movie 70', 'Thriller', 1987, 'Bong Joon-ho', 8.9, 103, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (71, 'Movie 71', 'Action', 2000, 'Hayao Miyazaki', 7.1, 148, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (72, 'Movie 72', 'Romance', 2022, 'Guillermo del Toro', 9.1, 118, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (73, 'Movie 73', 'Thriller', 1995, 'Martin Scorsese', 7.3, 98, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (74, 'Movie 74', 'Animation', 2011, 'Ridley Scott', 7.7, 197, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (75, 'Movie 75', 'Action', 1977, 'Anthony Russo', 9.4, 112, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (76, 'Movie 76', 'Action', 1976, 'James Cameron', 7.8, 183, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (77, 'Movie 77', 'Crime', 2008, 'Ridley Scott', 6.8, 163, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (78, 'Movie 78', 'Romance', 1972, 'Alfonso Cuaron', 7.8, 156, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (79, 'Movie 79', 'Animation', 1997, 'Quentin Tarantino', 9.3, 132, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (80, 'Movie 80', 'Drama', 2016, 'Anthony Russo', 7.4, 129, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (81, 'Movie 81', 'Animation', 1995, 'Alfonso Cuaron', 7.4, 106, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (82, 'Movie 82', 'Crime', 2012, 'Steven Spielberg', 8.5, 112, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (83, 'Movie 83', 'Crime', 2005, 'Pixar Team', 6.5, 126, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (84, 'Movie 84', 'Crime', 2020, 'James Cameron', 8.3, 131, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (85, 'Movie 85', 'Fantasy', 1998, 'David Fincher', 7.1, 150, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (86, 'Movie 86', 'Drama', 1988, 'Ridley Scott', 8.5, 169, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (87, 'Movie 87', 'Drama', 2022, 'Guillermo del Toro', 7.2, 129, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (88, 'Movie 88', 'Thriller', 1979, 'Christopher Nolan', 6.6, 150, 'UK');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (89, 'Movie 89', 'Fantasy', 1996, 'Anthony Russo', 8.4, 114, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (90, 'Movie 90', 'Fantasy', 1995, 'Hayao Miyazaki', 6.9, 178, 'USA');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (91, 'Movie 91', 'Drama', 2019, 'Steven Spielberg', 7.2, 192, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (92, 'Movie 92', 'Action', 2005, 'Hayao Miyazaki', 9.3, 105, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (93, 'Movie 93', 'Sci-Fi', 2021, 'Francis Ford Coppola', 8.5, 161, 'Italy');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (94, 'Movie 94', 'Fantasy', 2009, 'Pixar Team', 8.7, 154, 'Mexico');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (95, 'Movie 95', 'Fantasy', 1980, 'Alfonso Cuaron', 9.1, 147, 'France');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (96, 'Movie 96', 'Thriller', 2023, 'David Fincher', 7.3, 189, 'Germany');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (97, 'Movie 97', 'Thriller', 1987, 'Francis Ford Coppola', 6.7, 126, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (98, 'Movie 98', 'Romance', 1991, 'Martin Scorsese', 9.2, 100, 'Japan');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (99, 'Movie 99', 'Sci-Fi', 1984, 'Steven Spielberg', 8.6, 180, 'South Korea');
INSERT INTO Movies (MovieID, Title, Genre, ReleaseYear, Director, Rating, Duration, Country) VALUES (100, 'Movie 100', 'Drama', 1996, 'Steven Spielberg', 7.5, 149, 'Mexico');
