create database Sales_analysis;
use Sales_analysis;
select * from sales_data;

#1What is the total revenue generated by the superstore during the entire dataset period?
select sum(Sales) as total_revenue from sales_data;

#2What is the average daily sales revenue?
select avg(Sales) as average_daily_sales_revenue from sales_data group by date ('Order_Date');

#3Which product category generates the highest revenue?
select Category,sum(Sales) as total_sales from sales_data group by Category order by total_sales limit 1;

#4What is the distribution of sales across different regions?
select Region,sum(Sales) as total_Sales from sales_data group by Region;

#5Which product has the highest sales volume?
select Product_Name, SUM(Quantity) AS total_sales_volume from sales_data group by Product_Name order by total_sales_volume desc limit 1;

#6What is the most common payment method used by customers?
select Payment_Mode, COUNT(*) AS total_orders from sales_data group by Payment_Mode order by total_orders desc limit 1;

#7What is the average profit margin for products sold?
select avg(Profit) as average_profit_margin from sales_data;

select * from sales_data;
#8What is the average number of items per order?
select avg(Quantity) as avg_quantity from sales_data ;

#9How many orders were placed for each product category?
select Category,count(*) as orders from sales_data group by Category;

#25What is the distribution of sales across different segments?
select Segment,sum(Sales) as Sales from sales_data group by Segment;

#11How many unique customers have made purchases?
select count(distinct(Customer_Name)) as unique_customers  from sales_data;

#12What is the highest sales amount for a single transaction?
select max(sales) as highest_sale from sales_data;

#13What is the lowest sales amount for a single transaction?
select min(sales) as lowest_sales from sales_data;

#14How many different cities are represented in the dataset?
select count(distinct(City))as count_of_cities from sales_data;

#15How many orders were placed in each month?
select month(Order_Date),count(distinct(Order_Date)) as orders from sales_data group by month(Order_Date);

select * from sales_data;

#16How many orders were placed using each payment method?
select Payment_Mode,count(*) as orders from sales_data group by Payment_Mode;

#17How many orders were placed by each customer?
select Customer_Name,count(*) as orders from sales_data group by Customer_Name;

#18How many orders were placed from each state?
select State,count(*) as orders from sales_data group by State;

#19How many orders were placed from each city?
select City,count(*) as orders from sales_data group by City;

#20What is the average shipping time for orders?
select avg(DATEDIFF(Ship_Date, Order_Date)) as average_shipping_time from sales_data where Ship_Date is not null;

#21How many orders were placed on weekdays versus weekends?
select case when DAYOFWEEK(order_date) IN (1,7) then 'Weekend' else 'Weekday' end as day_type,
count(*) AS num_orders from  sales_data group by day_type;

#22What is the total profit generated from sales in each region?
select Region,sum(Profit) as profit from sales_data group by Region;

#23What is the total sales revenue generated in each state?
select State,sum(Sales) as total_sales from sales_data group by State;

#24How many unique product names are there in the dataset?
select distinct(Product_Name) as unique_P_name from sales_data;

#25How many orders had negative profit?
select count(*) as negative_profit from sales_data where Profit<0;
